#
# 数据库备份
# Time: 2015-04-05 16:28
# Type: 1.0
# author: 罗家辉
# --------------------------------------------------------


DROP TABLE IF EXISTS tbl_admin2;
CREATE TABLE tbl_admin2 (
  id int(11) NOT NULL AUTO_INCREMENT,
  username varchar(10) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `password` varchar(50) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  checked int(11) NOT NULL,
  PRIMARY KEY (id)
) ENGINE=MyISAM AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS tbl_event;
CREATE TABLE tbl_event (
  id int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) COLLATE utf8_bin NOT NULL,
  img varchar(255) COLLATE utf8_bin DEFAULT NULL,
  intro text COLLATE utf8_bin,
  `year` int(11) DEFAULT NULL,
  `type` int(11) DEFAULT NULL,
  `month` int(11) DEFAULT NULL,
  `day` int(11) DEFAULT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB AUTO_INCREMENT=45 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

INSERT INTO tbl_admin2 VALUES('1','admin','21232f297a57a5a743894a0e4a801fc3','1');

INSERT INTO tbl_event VALUES('18','2013','','2013','1901','0','12','30');
INSERT INTO tbl_event VALUES('19','201301','','201301','2013','1','1','10');
INSERT INTO tbl_event VALUES('20','201302','','201302','2013','1','2','5');
INSERT INTO tbl_event VALUES('21','2014','','201401','2014','1','4','4');
INSERT INTO tbl_event VALUES('22','2014','','2014','1902','0','12','31');
INSERT INTO tbl_event VALUES('24','人中国最早提出修建铁路的人','upload/20150405/20150405125453_13039.jpg','<span style=\"font-size:10.5pt;font-family:宋体;\">&nbsp; &nbsp;<span style=\"font-size:18px;\">&nbsp;</span><span style=\"font-size:18px;\">在近代中国，首先提出修建铁路的是太平天国的干王洪仁玕，他在</span></span><span \"=\"\" style=\"font-size:18px;\">1859</span><span style=\"font-family:宋体;font-size:18px;\">年撰写的《资政新篇》中提出一套统筹全局的革新方案，主张发展交通运输业，修筑道路，制造火车轮船等，并勾画出发展近代铁路、公路交通的蓝图。他建议：</span><span \"=\"\" style=\"font-size:18px;\">&nbsp; </span><span style=\"font-family:宋体;font-size:18px;\">“先于二十一省，通二十一条大路，以为全国之脉络”，这样一来，</span><span \"=\"\" style=\"font-size:18px;\">&nbsp; </span><span style=\"font-family:宋体;font-size:18px;\">“虽三四千里之遥，亦可朝发夕至”。洪仁玕在《资政新篇》中提出：</span><span \"=\"\" style=\"font-size:18px;\">&nbsp; </span><span style=\"font-family:宋体;font-size:18px;\">“兴车马之利，以利便轻捷为妙。倘有能造如外邦火轮车，一日夜能行七八千里者，准自专其利，限满准他人仿造。”他的这些主张和建议，比起后来改良派、洋务派等陆续提出的发展民族工商业的主张，不仅早了二三十年，而且也更为全面和彻底。</span>','1905','1','4','11');
INSERT INTO tbl_event VALUES('25','皇家祭祖专线---西陵铁路','upload/20150405/20150405131112_46531.png','<span style=\"font-size:10.5pt;font-family:;\" \"=\"\">&nbsp; &nbsp; &nbsp;<span style=\"font-size:18px;\"> &nbsp;1902</span></span><span style=\"font-size:18px;font-family:宋体;\">年，历经磨难的慈禧太后从两安回到北京后，想在第二年的清明节去西陵祭祖，由于她有了第一次乘坐火车舒适、平稳、快速的初步感受，决定修建从高碑店直达西陵的铁路，并委派袁世凯办理这条铁路的修建事宜。此路由高碑店附近的新城起经涞水至易县的梁各庄，全长</span><span style=\"font-size:18px;\" \"=\"\">42.5</span><span style=\"font-size:18px;font-family:宋体;\">公里，又称新易铁路。由于英法两国也想争夺此路的修筑权，袁世凯不得不采取自主修建的办法，交由詹天佑负责修路工程。詹天佑接受该任务时，正值隆冬季节，距慈禧太后祭祖只有短短的</span><span style=\"font-size:18px;\" \"=\"\">6</span><span style=\"font-size:18px;font-family:宋体;\">个月，詹天佑克服困难，经过周密部署，带领筑路工人日夜加班，用临时搭建便桥以先行通车，然后再加固的办法，于</span><span style=\"font-size:18px;\" \"=\"\">1903</span><span style=\"font-size:18px;font-family:宋体;\">年</span><span style=\"font-size:18px;\" \"=\"\">4</span><span style=\"font-size:18px;font-family:宋体;\">月谒陵之前通车。</span>','1903','1','4','25');
INSERT INTO tbl_event VALUES('26','沪宁铁路','upload/20150405/20150405131503_85994.png','<p>\r\n	<span>&nbsp;<span style=\"font-size:18px;\">&nbsp; &nbsp; &nbsp;1908</span></span><span style=\"font-family:宋体;font-size:18px;\">年沪宁铁路全线通车，线路全长</span><span style=\"font-size:18px;\">311</span><span style=\"font-family:宋体;font-size:18px;\">公里，由上海北站至南京下关站，沿途共设车站</span><span style=\"font-size:18px;\">37</span><span style=\"font-family:宋体;font-size:18px;\">个。较大车站有上海、昆山、苏州、无锡、常州、丹阳、镇江、龙潭、南京等站,</span><span style=\"font-family:宋体;font-size:18px;\">行车时间需要</span><span style=\"font-size:18px;\">10</span><span style=\"font-family:宋体;font-size:18px;\">个小时。</span><span style=\"font-size:18px;\">1908</span><span style=\"font-family:宋体;font-size:18px;\">年开行旅客列车</span><span style=\"font-size:18px;\">7</span><span style=\"font-family:宋体;font-size:18px;\">对，</span><span style=\"font-size:18px;\">1910</span><span style=\"font-family:宋体;font-size:18px;\">年开行旅客列车</span><span style=\"font-size:18px;\">6</span><span style=\"font-family:宋体;font-size:18px;\">对，每逢星期六南京开夜快车</span><span style=\"font-size:18px;\">1</span><span style=\"font-family:宋体;font-size:18px;\">对，星期日由上海返同南京。票价分一等</span><span style=\"font-size:18px;\">6</span><span style=\"font-family:宋体;font-size:18px;\">分、二等</span><span style=\"font-size:18px;\">3</span><span style=\"font-family:宋体;font-size:18px;\">分、三等</span><span style=\"font-size:18px;\">2</span><span style=\"font-family:宋体;font-size:18px;\">分，后增设四等客车，票价为</span><span style=\"font-size:18px;\">0.75</span><span style=\"font-family:宋体;font-size:18px;\">分。</span><span style=\"font-size:18px;\">1928</span><span style=\"font-family:宋体;font-size:18px;\">年至</span><span style=\"font-size:18px;\">1949</span><span style=\"font-family:宋体;font-size:18px;\">年间，因国民政府在南京定都，故更名为“京沪铁路”。</span>\r\n</p>','1908','1','5','24');
INSERT INTO tbl_event VALUES('27','早起列车上的餐饮服务','upload/20150405/20150405131944_33568.png','<p style=\"text-indent:21.75pt;\">\r\n	<span style=\"font-family:宋体;\">餐饮是早期铁路客运服务的一部分。沪宁铁路开通运营初期，客车上供应茶点，在头等、二等客车上，不管旅客要不要，只要一坐定，就会给你泡上一杯茶，茶价为</span><span>4</span><span style=\"font-family:宋体;\">角；三等客车用茶壶，每壶</span><span>2</span><span style=\"font-family:宋体;\">角；茶杯、茶壶上都印有广告。餐车上的食品供应由沪宁铁路公司承包给上海几家有名的西餐社和大饭店经营。每当列车启动，侍者即手持菜单先到头等车，向旅客一一询问“要吃西餐吗？”如果要，就会在你的案上铺上桌布，摆上刀又，一道道的上菜；若你只需简单的份饭，就铺上一块小桌布。二等车里不铺桌布，三等车由侍者送餐且价格合理，这项餐茶服务也是列车营业收入之一。</span>\r\n</p>','1902','1','6','3');
INSERT INTO tbl_event VALUES('28','劣质的黄河大桥','upload/20150405/20150405132442_07306.jpg','<p style=\"text-indent:21.0pt;\">\r\n	<span style=\"font-size:18px;\">1903</span><span style=\"font-family:宋体;font-size:18px;\">年在修建京汉铁路郑州黄河大桥时，比利时公司不顾工程质量，只顾图快省钱，在设计前对洪水冲刷认识不足，桥基埋深浅，也没有考虑火车行驶时的震动力，以致桥梁修建质量不高，为行车安全理下隐患。施工期间就有</span><span style=\"font-size:18px;\">8</span><span style=\"font-family:宋体;font-size:18px;\">个桥墩曾被洪水冲毁，大桥建成后，比利时公司只保固</span><span style=\"font-size:18px;\">1 5</span><span style=\"font-family:宋体;font-size:18px;\">年，行车时速仅为</span><span style=\"font-size:18px;\">10-15</span><span style=\"font-family:宋体;font-size:18px;\">公里。大桥建成不久，桥墩就出现倾斜，黄河中大量的抛石高出水面，险情时有发生。</span>\r\n</p>','1903','1','1','8');
INSERT INTO tbl_event VALUES('30','“断桥”的由来','upload/20150405/20150405132659_30364.jpg','<p style=\"text-indent:21.0pt;\">\r\n	<span style=\"font-size:18px;\">1907</span><span style=\"font-family:宋体;font-size:18px;\">年，日本胁迫清政府同意在鸭绿江上修建铁路大桥，</span><span style=\"font-size:18px;\">1909</span><span style=\"font-family:宋体;font-size:18px;\">年</span><span style=\"font-size:18px;\">7</span><span style=\"font-family:宋体;font-size:18px;\">月大桥动工，</span><span style=\"font-size:18px;\">1911</span><span style=\"font-family:宋体;font-size:18px;\">年</span><span style=\"font-size:18px;\">11</span><span style=\"font-family:宋体;font-size:18px;\">月竣工，安奉铁路同朝鲜铁路接轨，形成了从中国东北连接朝鲜半岛的一条运输线。日本通过这条铁路，将东北的矿产、木材、农产品等通过鸭绿江铁路大桥源源不断运往日本。该桥由当时日本驻朝鲜总督府铁路局负责修建，从中国方向数第四孑</span><span style=\"font-size:18px;\">L</span><span style=\"font-family:宋体;font-size:18px;\">为开闭式钢梁，以四号桥墩为轴，该钢梁可旋转</span><span style=\"font-size:18px;\">90</span><span style=\"font-family:宋体;font-size:18px;\">度，便于过往的大型船只航行。</span><span style=\"font-size:18px;\">1943</span><span style=\"font-family:宋体;font-size:18px;\">年</span><span style=\"font-size:18px;\">4</span><span style=\"font-family:宋体;font-size:18px;\">月，日本在此上游不足百米处建成第二座铁路大桥，将第一座桥改为公路桥。抗美援朝战争期间被美军飞机炸断，成为废桥，中方一侧所剩四孔残桥保留至今，称为“断桥”。</span>\r\n</p>','1907','1','11','25');
INSERT INTO tbl_event VALUES('31','盲肠铁路','upload/20150405/20150405132835_46767.png','<p style=\"text-indent:21.0pt;\">\r\n	<span style=\"font-size:18px;\">1905</span><span style=\"font-family:宋体;font-size:18px;\">年，福建省华侨筹资组建铁路公司，修建漳厦铁路。</span><span style=\"font-size:18px;\">1907</span><span style=\"font-family:宋体;font-size:18px;\">年漳厦铁路嵩屿至江东桥段开工，全长仅</span><span style=\"font-size:18px;\">28</span><span style=\"font-family:宋体;font-size:18px;\">公里。起点设在江东桥站，距离漳州还有</span><span style=\"font-size:18px;\">17</span><span style=\"font-family:宋体;font-size:18px;\">公里多的旱路，从漳州前往厦门的旅客，要跑</span><span style=\"font-size:18px;\">17</span><span style=\"font-family:宋体;font-size:18px;\">公里多的路程，到江东桥买票上车，终点站嵩屿距厦门也有</span><span style=\"font-size:18px;\">3</span><span style=\"font-family:宋体;font-size:18px;\">公里多的海路，旅客搭乘小火轮渡海后再乘火车到江东桥，短短的一条铁路，前不过海，后不过江，如同肓肠一般，人称“盲肠铁路”，如此这般的漳厦铁路，毫无交通便利可言，但它是</span><span style=\"font-size:18px;\">20</span><span style=\"font-family:宋体;font-size:18px;\">世纪初期福建省唯一的铁路。</span>\r\n</p>','1905','1','8','10');
INSERT INTO tbl_event VALUES('32','京奉铁路的前世今生','upload/20150405/20150405132958_39013.png','<p>\r\n	<span style=\"font-family:宋体;font-size:18px;\">这是一条由北京经天津出山海关到沈阳的干线铁路，始建于</span><span style=\"font-size:18px;\">1881</span><span style=\"font-family:宋体;font-size:18px;\">年修建的唐胥铁路，此路为关内外铁路之发端。它不断延伸修建了</span><span style=\"font-size:18px;\">30</span><span style=\"font-family:宋体;font-size:18px;\">余年，先后于</span><span style=\"font-size:18px;\">1887</span><span style=\"font-family:宋体;font-size:18px;\">年展筑至芦台后，改称唐芦铁路；</span><span style=\"font-size:18px;\">1888</span><span style=\"font-family:宋体;font-size:18px;\">年修筑至天津后，改称唐津铁路；</span><span style=\"font-size:18px;\">1894</span><span style=\"font-family:宋体;font-size:18px;\">年天津至山海关铁路通车，因山海关在历史上曾称“榆关”，所以又称津榆铁路，</span><span style=\"font-size:18px;\">1\r\n897</span><span style=\"font-family:宋体;font-size:18px;\">年津榆铁路由天津经津卢铁路（天津至卢沟桥）延伸至北京城外马家堡，后经津卢铁路展筑至北京正阳门，改称京津铁路；之后津卢铁路、津榆铁路合并，改称关内外铁路；</span><span style=\"font-size:18px;\">1907</span><span style=\"font-family:宋体;font-size:18px;\">年关内外铁路延伸修建至奉天省府附近的皇</span>\r\n</p>\r\n<p>\r\n	<span style=\"font-family:宋体;font-size:18px;\">姑屯，改称京奉铁路；</span><span style=\"font-size:18px;\">1912</span><span style=\"font-family:宋体;font-size:18px;\">年通车至沈阳新站；</span><span style=\"font-size:18px;\">1929</span><span style=\"font-family:宋体;font-size:18px;\">年当奉天省改称辽宁省后称北宁（北平至辽宁）铁路；</span><span style=\"font-size:18px;\">1945</span><span style=\"font-family:宋体;font-size:18px;\">年抗战胜利后改称京沈铁路；现与沈哈铁路合称京哈铁路。</span>\r\n</p>','1907','1','8','18');
INSERT INTO tbl_event VALUES('33','天津北站','upload/20150405/20150405133131_01306.png','<p style=\"text-indent:21.0pt;\">\r\n	<span style=\"font-size:18px;\">1892</span><span style=\"font-family:宋体;font-size:18px;\">年天津第一个火车站老龙头火车站建成，庚子事变后，老龙头火车站被划人俄租界，唯一的火车站受到外国人控制，</span><span style=\"font-size:18px;\">1902</span><span style=\"font-family:宋体;font-size:18px;\">年时任直隶总督兼北洋大臣的袁世凯，经常往来天津与北京两地，出入车站也要看外国人脸色，为此感到十分不满，遂下令在老龙头火车站以北</span><span style=\"font-size:18px;\">4</span><span style=\"font-family:宋体;font-size:18px;\">公里处修建新车站，</span><span style=\"font-size:18px;\">1903</span><span style=\"font-family:宋体;font-size:18px;\">年完工。</span><span style=\"font-size:18px;\">1910</span><span style=\"font-family:宋体;font-size:18px;\">年京奉铁路与津浦铁路在天津北站举行联轨典礼，该站</span><span style=\"font-size:18px;\">1</span><span style=\"font-family:宋体;font-size:18px;\">、</span><span style=\"font-size:18px;\">2</span><span style=\"font-family:宋体;font-size:18px;\">、</span><span style=\"font-size:18px;\">3</span><span style=\"font-family:宋体;font-size:18px;\">股道为津浦线列车到发用，其余为京奉路列车到发用。</span><span style=\"font-size:18px;\">1937</span><span style=\"font-family:宋体;font-size:18px;\">年抗战爆发天津沦陷后，车站于</span><span style=\"font-size:18px;\">1938</span><span style=\"font-family:宋体;font-size:18px;\">年更名为天津总站，其用意为津浦、京奉两路所共用。</span> \r\n</p>','1938','1','5','8');
INSERT INTO tbl_event VALUES('34','别致的京汉铁路车票','upload/20150405/20150405133226_15277.png','<p>\r\n	<span>&nbsp; &nbsp; &nbsp;&nbsp;<span style=\"font-size:18px;\">1906</span></span><span style=\"font-family:宋体;font-size:18px;\">年京汉铁路通车运营初期，客运量不大，每周只开行北京至汉口快车</span><span style=\"font-size:18px;\">1</span><span style=\"font-family:宋体;font-size:18px;\">对，全程运行</span><span style=\"font-size:18px;\">36</span><span style=\"font-family:宋体;font-size:18px;\">小时</span><span style=\"font-size:18px;\">45</span><span style=\"font-family:宋体;font-size:18px;\">分钟，列车设有卧铺和餐车；普通旅客列车，每日</span><span style=\"font-size:18px;\">1</span><span style=\"font-family:宋体;font-size:18px;\">对，全程运行</span><span style=\"font-size:18px;\">58</span><span style=\"font-family:宋体;font-size:18px;\">小时</span><span style=\"font-size:18px;\">16</span><span style=\"font-family:宋体;font-size:18px;\">分钟，为白天行车，在安阳与信阳停车过夜；此外还开行北京至正定、塘沽至正定慢车</span><span style=\"font-size:18px;\">1</span><span style=\"font-family:宋体;font-size:18px;\">对。旅客列车车票伴随着这条铁路的运营而诞生了，这张车票上面的法文是：北京至汉口铁路，中间印有京汉铁路使用的蒸汽机车，两旁是象征中华民族强盛的龙饰图案，中间覆印票价，反映该路尽管是外国人修建的，但路权是属于中国的。</span> \r\n</p>','1906','1','6','17');
INSERT INTO tbl_event VALUES('35','“潮汕铁路业”的背后','upload/20150405/20150405134022_10358.png','<p>\r\n	<span>&nbsp; &nbsp; &nbsp;<span style=\"font-size:18px;\">&nbsp;</span><span style=\"font-size:18px;\">1903</span></span><span style=\"font-family:宋体;font-size:18px;\">年，南洋华侨张煜南、张鸿南兄弟向清政府提出要求建筑潮汕铁路的申请，慈禧亲自批准，同意修建，并签订</span><span style=\"font-size:18px;\">50</span><span style=\"font-family:宋体;font-size:18px;\">年后收归国有的条约，开创了华侨修筑铁路之始。这条铁路是潮州通往闽西汀州（长汀）及粤东嘉应州（梅县）等地的必经之地，南起汕头，北迄潮安，</span> \r\n</p>\r\n<p>\r\n	<span style=\"font-family:宋体;font-size:18px;\">全长</span><span style=\"font-size:18px;\">39</span><span style=\"font-family:宋体;font-size:18px;\">公里，后来又加筑了潮州西门至意溪码头支线，共计</span><span style=\"font-size:18px;\">42</span><span style=\"font-family:宋体;font-size:18px;\">公里。詹天佑作为潮汕铁路总工程司前来勘测、设计。后与日本人意见不统一，遭到排斥而离职。之后日本人以</span><span style=\"font-size:18px;\">10</span><span style=\"font-family:宋体;font-size:18px;\">万元的工程造价承包修筑潮汕铁路，并盗用了詹天佑的设计方案。在修路中，发生了沿线百姓打死日本人的事件，在日本人的逼迫下，清政府采用了李代桃僵之策，制造了一起残害人命的冤假错案，史称“潮汕铁路案”。</span> \r\n</p>','1903','1','8','28');
INSERT INTO tbl_event VALUES('36','几经波折的罗湖铁路桥','upload/20150405/20150405134227_62744.png','<p>\r\n	<span>&nbsp;<span style=\"font-size:18px;\">&nbsp; &nbsp; &nbsp;</span></span><span style=\"font-family:宋体;font-size:18px;\">始建于</span><span style=\"font-size:18px;\">1906</span><span style=\"font-family:宋体;font-size:18px;\">年的罗湖桥包括铁路桥和人行桥，该桥为</span><span style=\"font-size:18px;\">3</span><span style=\"font-family:宋体;font-size:18px;\">孔，两端孔为</span><span style=\"font-size:18px;\">6.71</span><span style=\"font-family:宋体;font-size:18px;\">米钢槽梁，中孔为</span><span style=\"font-size:18px;\">32</span><span style=\"font-family:宋体;font-size:18px;\">米钢桁梁。该桥北岸的桥座及桥墩由中国方面修建，南段的桥座、桥墩及全</span> \r\n</p>\r\n<p>\r\n	<span style=\"font-family:宋体;font-size:18px;\">桥的钢梁由英国修建。据《罗湖铁路历史》及《九广铁路的历史》记载，在第二次世界大战期间，英军为阻止日军进攻，于</span><span style=\"font-size:18px;\">1941</span><span style=\"font-family:宋体;font-size:18px;\">年拆毁罗湖铁路桥及九广铁路。日军占领期间，对罗湖铁路桥及九广铁路进行了重建，日军撤离时，又拆毁了罗湖铁路桥，现桥为后来重建。</span> \r\n</p>','1906','1','7','18');
INSERT INTO tbl_event VALUES('37','行车安全的大功臣—大石桥','upload/20150405/20150405134341_57373.png','<p>\r\n	<span>&nbsp; &nbsp; &nbsp;&nbsp;1907</span><span style=\"font-family:宋体;\">年正太铁路建成通车后，由于过往的行人和车辆必须穿越铁路，而铁路沿线又没有安</span><span style=\"font-family:宋体;line-height:1.5;\">全保护设施，火车撞伤、轧死人畜的事故时有发生。鉴于此种情况，铁路员工和各界人士纷纷联名上书掌管正太铁路权的法国总办，要求拨款修建一座跨越铁路的桥梁。但法国总办对此却置之不理，正太铁路员工发起了捐献工资，集资建桥的活动，各界有识之士也纷纷慷慨解囊。修桥款筹齐后，由唐山工匠赵兰承担了全部工程设计施工任务。在短短的几个月里，工匠们就将这座桥建成了，因该桥桥身系大青石砌成，故名大石桥。其中两孔采用钢梁外，其余均采用我国传统的石拱结构，桥面坡度平缓，桥体坚固美观，桥头两端各塑二尊石狮雕像。大石桥建成后，正太铁路从桥下行驶，行人和车辆从桥上通过，方便了东西方向的交通，铁路沿线事故大为减少。</span> \r\n</p>','1907','1','9','25');
INSERT INTO tbl_event VALUES('38','国人修路   震惊中外','upload/20150405/20150405134458_93630.png','<p>\r\n	<span>&nbsp; &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;<span style=\"font-size:18px;\">1909</span><span style=\"font-family:宋体;font-size:18px;\"><span style=\"font-size:18px;\">年</span></span><span style=\"font-size:18px;\">9</span><span style=\"font-family:宋体;font-size:18px;\"><span style=\"font-size:18px;\">月</span></span><span style=\"font-size:18px;\">24</span><span style=\"font-family:宋体;font-size:18px;\"><span style=\"font-size:18px;\">日</span></span><span style=\"font-family:宋体;font-size:18px;\">一条由中国人自己勘测、自己设计、自己施工修建的干线铁路——京</span></span><span style=\"font-family:宋体;font-size:18px;\">张铁路，比原定计划提前</span><span style=\"font-size:18px;\">2</span><span style=\"font-family:宋体;font-size:18px;\">年建成。这是当时我国修筑成本最低、质量良好的铁路。</span><span style=\"font-size:18px;\">10</span><span style=\"font-family:宋体;font-size:18px;\">月</span><span style=\"font-size:18px;\">2</span><span style=\"font-family:宋体;font-size:18px;\">日，京张铁路在南口举行了盛大的通车典礼，有众多中外来宾参加典礼，并在南口车站举行</span><span style=\"font-family:宋体;font-size:18px;line-height:1.5;\">通车剪彩仪式。京张铁路总办兼总工程司詹天佑、广东番禹朱君淇等人在庆祝通车仪式上发表演说。京张铁路的建成，在国内外引起轰动，其意义远远超出铁路工程技术领域，为深受外国势力欺辱的中国人争了一口大气。</span> \r\n</p>','1909','1','9','24');
INSERT INTO tbl_event VALUES('39','京张铁路行车时刻价目表','upload/20150405/20150405134605_85416.png','<p>\r\n	<span style=\"font-family:宋体;font-size:18px;\">&nbsp; &nbsp;&nbsp;京张铁路自</span><span style=\"font-size:18px;\">1905</span><span style=\"font-family:宋体;font-size:18px;\">年</span><span style=\"font-size:18px;\">10</span><span style=\"font-family:宋体;font-size:18px;\">月</span><span style=\"font-size:18px;\">2</span><span style=\"font-family:宋体;font-size:18px;\">日</span><span style=\"font-family:宋体;font-size:18px;\">在丰台站东侧柳村插标动工，于</span><span style=\"font-size:18px;\">1906</span><span style=\"font-family:宋体;font-size:18px;\">年</span><span style=\"font-size:18px;\">9</span><span style=\"font-family:宋体;font-size:18px;\">月</span><span style=\"font-size:18px;\">30</span><span style=\"font-family:宋体;font-size:18px;\">日</span><span style=\"font-family:宋体;font-size:18px;\">修通至南口车站，前后仅用了不到一年的时间。并在通车运营前，詹天佑先生就制定了客运、货运票价及货物等级分类标准等运输规定，随后此段铁路即开办运输营业。这张京张铁路开通运营时的行车时刻价目表，记录了当时客车开行时间、起讫站，开行对毁、运行速度、头等客票</span><span style=\"font-family:宋体;line-height:1.5;font-size:18px;\">价目等信息，见证了一百多年前国民经济以及国人生活的历史，伴随着火车的轰鸣，为内外来人员往来及通商贸易带来了极大便利。</span> \r\n</p>','1905','1','10','2');
INSERT INTO tbl_event VALUES('40','中国第一所铁路大学','upload/20150405/20150405134717_43007.png','<p style=\"text-indent:21.0pt;\">\r\n	<span style=\"font-family:宋体;font-size:18px;\">&nbsp;清政府邮传部于</span><span style=\"font-size:18px;\">1 909</span><span style=\"font-family:宋体;font-size:18px;\">年创办北京铁路管理传习所，这是中国历史上为维护国家铁路权益而创办的第一所专门培养管理人才的高等学府。传习所开设有一年制铁路管理英文简易班和德文简易班，三年制铁路英文高等班、法文高等班。之后又相继开设邮电班、统计班、电信班等专业科班。</span><span style=\"font-size:18px;\">1910</span><span style=\"font-family:宋体;font-size:18px;\">年铁路管理传习所改名为交通传习所。</span><span style=\"font-size:18px;\">1921</span><span style=\"font-family:宋体;font-size:18px;\">年该传习所与上海、唐山两所工业专门学校合并，定名为交通大学，下设京、沪、唐三校，北京交大当时称交通大学北京学校，</span><span style=\"font-size:18px;\">1923</span><span style=\"font-family:宋体;font-size:18px;\">年更名为北京交通大学。新中国成立后，经政务院批准定名为北方交通大学，毛泽东主席亲笔题写了校名。</span> \r\n</p>','1909','1','2','19');
INSERT INTO tbl_event VALUES('41','唯能可贵的一段路','upload/20150405/20150405134840_19053.png','<p>\r\n	<span>&nbsp; <span style=\"font-size:18px;\">&nbsp; &nbsp; &nbsp;1909</span></span><span style=\"font-family:宋体;font-size:18px;\">年</span><span style=\"font-size:18px;\">10</span><span style=\"font-family:宋体;font-size:18px;\">月川汉铁路在宜昌举行开工典礼，首先修筑宜昌至万县段，分</span><span style=\"font-size:18px;\">10</span><span style=\"font-family:宋体;font-size:18px;\">段同时开工。宜万段沿长江三峡而行，沿途连山大岭，地势险峻，工程异常艰巨，成千上万的筑路工人在没有开挖机械的情况下，用几乎原始的办法劈山修路。正当紧张的施工时，商办川汉铁路公司内部发生矛盾，管理混乱，争夺权势。在这种社会环境和技术条件下，宜万段重点工</span><span style=\"font-family:宋体;font-size:18px;\">程东兴界岭隧道已开挖三分之一，部分路基、桥涵、站房已经建成，并修通了宜昌至小溪塔仅</span><span style=\"font-size:18px;\">7.5</span><span style=\"font-family:宋体;font-size:18px;\">公里一段，也实属可贵。</span> \r\n</p>','1909','1','10','24');
INSERT INTO tbl_event VALUES('42','辛亥秋保路死事纪念碑','upload/20150405/20150405134939_67222.png','<p>\r\n	<span>&nbsp;<span style=\"font-size:18px;\">&nbsp; &nbsp; &nbsp;1913</span></span><span style=\"font-family:宋体;font-size:18px;\">年川路总公司为纪念</span><span style=\"font-size:18px;\">1910</span><span style=\"font-family:宋体;font-size:18px;\">年四川保路同志会组织的，反对清政府出卖汉铁筑路权斗争中死难的烈士修建的纪念碑。聘请王楠为总监工，负责图纸设计和施工。该纪念碑高</span><span style=\"font-size:18px;\">31.85</span><span style=\"font-family:宋体;font-size:18px;\">米，由台基、碑座、碑身、宝顶四部分组成。碑台仿照铁路月台修建，呈圆柱形；碑座四面刻有机车、路轨、信号灯、转辙器和自动联接器等浮雕图案，象征着川汉铁路；碑身呈方椎体，四面均嵌有长条青石，携刻楷、草、行、隶</span><span style=\"font-size:18px;\">4</span><span style=\"font-family:宋体;font-size:18px;\">种书体手书“辛亥秋保路死事纪念碑”</span><span style=\"font-size:18px;\">10</span><span style=\"font-family:宋体;font-size:18px;\">个字，每字高约</span><span style=\"font-size:18px;\">1</span><span style=\"font-family:宋体;font-size:18px;\">米见方，为清民初四川书法家张夢阶、颜凯、吴伯朅、赵熙等人所书。孙中山先生在高度评价四川人民在辛亥革命中的历史功绩时曾指出：“若没有四川保路同志会的起义，武昌革命或者要迟一年半载的。”</span> \r\n</p>','1913','1','8','29');
INSERT INTO tbl_event VALUES('43','123','','123456','1750','1','10','8');
INSERT INTO tbl_event VALUES('44','55555','','55555','1600','1','12','1');

